# Generated by Django 4.1.7 on 2023-05-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estimation", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
