# Generated by Django 4.1.7 on 2023-05-13 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Estimation", "0004_alter_statmodel_resist"),
    ]

    operations = [
        migrations.AddField(
            model_name="statmodel",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="statmodel",
            name="reaction",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
