# Generated by Django 4.1.7 on 2023-05-13 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Estimation", "0005_statmodel_user_id_alter_statmodel_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statmodel",
            name="user_id",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
