# Generated by Django 4.1.7 on 2023-05-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Estimation", "0007_statmodel_arts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statmodel",
            old_name="defence",
            new_name="defense",
        ),
        migrations.RenameField(
            model_name="statmodel",
            old_name="defence_percent",
            new_name="defense_percent",
        ),
    ]
