# Generated by Django 4.1.7 on 2023-04-03 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0002_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("NA", "Normal Attack"),
                            ("HA", "Hold Attack"),
                            ("E", "Elementary Skill"),
                            ("ULT", "Elementary Burst"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "lvl",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
            ],
        ),
    ]
