# Generated by Django 4.1.7 on 2023-04-03 22:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0003_characterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("NA", "Normal Attack"),
                            ("HA", "Hold Attack"),
                            ("E", "Elementary Skill"),
                            ("ULT", "Elementary Burst"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GenshinStorage.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lvl",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(13),
                        ]
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GenshinStorage.skill",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CharacterData",
        ),
    ]
