# Generated by Django 4.1.7 on 2023-04-03 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0005_character_weapon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="description",
        ),
    ]
