# Generated by Django 4.1.7 on 2023-04-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0006_remove_character_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="description",
            field=models.TextField(default="1"),
            preserve_default=False,
        ),
    ]
