# Generated by Django 4.1.7 on 2023-04-23 17:18

import GenshinStorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0007_character_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="big_image",
            field=models.ImageField(null=True, upload_to=GenshinStorage.models.char_big_image_file_path),
        ),
        migrations.AddField(
            model_name="character",
            name="small_image",
            field=models.ImageField(null=True, upload_to=GenshinStorage.models.char_small_image_file_path),
        ),
    ]
