# Generated by Django 4.1.7 on 2023-04-23 23:20

import GenshinStorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0008_character_big_image_character_small_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=GenshinStorage.models.element_image_file_path,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="element",
        ),
    ]
