# Generated by Django 4.1.7 on 2023-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0010_character_element"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="element",
        ),
        migrations.RemoveField(
            model_name="element",
            name="id",
        ),
        migrations.AlterField(
            model_name="element",
            name="name",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
