# Generated by Django 4.1.7 on 2023-04-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0011_remove_character_element_remove_element_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="element",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="GenshinStorage.element",
            ),
        ),
    ]
