# Generated by Django 4.1.7 on 2023-04-24 18:52

import GenshinStorage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0014_character_rarity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "name",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                (
                    "icon_light",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=GenshinStorage.models.location_light_image_file_path,
                    ),
                ),
                (
                    "icon_dark",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=GenshinStorage.models.location_dark_image_file_path,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "name",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=GenshinStorage.models.weapon_image_file_path,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="character",
            name="location",
        ),
        migrations.RemoveField(
            model_name="character",
            name="weapon",
        ),
        migrations.AlterField(
            model_name="element",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=GenshinStorage.models.element_image_file_path,
            ),
        ),
    ]
