# Generated by Django 4.1.7 on 2023-05-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GenshinStorage", "0017_alter_character_location_alter_character_weapon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skilldata",
            name="skill",
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.DeleteModel(
            name="SkillData",
        ),
    ]
